### PR TITLE
Replace ConcurrentLinkedQueue by Agrona bounded MPMC

### PR DESCRIPTION
**Pull request by guidomedina**
Replace ConcurrentLinkedQueue by Agrona bounded Multiple Producer-Multiple Consumer.

The reasoning for this is GC, users using the default queue if sending/receiving many small messages will generate GC because of the linked data structure.

No dependency is needed because `akka-remote` depends on `aeron` which depends on `agrona`

**Note:** I have also updated few dependencies like Akka, Kryo, etc, also it fixes #117

### CODE REVIEW

**Comment by guidomedina** [comment]
@luben ping :D

**Comment by guidomedina** [comment]
@luben I see SBT deprecated warning and stuff, maybe it is a good time to update SBT stuff?
Combining non-blocking GC free queue with Unsafe should be the right combo for a great performance.

**Comment by nvollmar** [comment]
@guidomedina sbt and dependencies have been updated meanwhile

**Comment by guidomedina** [comment]
I have removed changes that don't apply anymore and re-pushed to do exactly what the branch states which is to replace the example queue with a non-blocking queue which depends on a dependency pulled by the current `akka-remote`

**Comment by guidomedina** [comment]
The gaining should be minimal in comparison to the serialization and I/O costs but still there is some gaining in that these queues are Lock/GC free, basically there is no allocation; they act as a circular buffer; similar to https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/MpmcArrayQueue.java

They all follow the same algorithm from a lock-free producer consumer paper, they are guarantee to be much faster than the standard Java `ConcurrentQueue`, here is the source of all of them http://www.1024cores.net/home/lock-free-algorithms/queues

**Comment by guidomedina** [comment]
Also, there shouldn't be any impact because we use here for a pool, meaning that we never pick and getting null is fine, a new Kryo instance is then created and pushed back to the queue or discarded if the queue is full, all in a non-blocking manner.

**Comment by guidomedina** [comment]
Another aspect that might be of interest since I see you guys on the FinTech, what motivated this was that this has been part of a distributed semi low latency trading FX system I developed 3 years ago, we replaced all of our actor default queues for GC-free non-blocking implementations, full cycle of order execution never exceed 1ms or 2ms which includes the time of traveling between 3 Akka nodes using Artery/Aeron.

**Comment by nvollmar** [comment]
lgtm

**Pull request merged**
