### PR TITLE
Add akka-kryo-serialization-shaded, without external dependency over ASM

### PR DESCRIPTION
**Pull request by pacien**
Straightforward fix for issue #113.

### CODE REVIEW

**Comment by romix** [comment]
Hmm. I was thinking more in the direction of producing an additional JAR with a shaded kryo, so that we have the usual akka-kryo-serialization and the akka-kryo-serialization-shaded, or something like that? Some people may not like the idea of using kryo-shaded by default, because they use the same version of Kryo for many different things.

WDYT? Could you try to enhance your solution to handle this?

**Comment by Pacien** [comment]
Thank you for your feedback.

~~I modified the build file as suggested to output both `akka-kryo-serialization` and `akka-kryo-serialization-shaded`.~~ For some reason, it's only publishing the first one. Working on it.

**Comment by Pacien** [comment]
Got it to work without aggregation.

`akka-kryo-serialization` can be built and published as usual.
`akka-kryo-serialization-shaded` tasks have to be prefixed with `akka-kryo-serialization-shaded/`.

**Comment by romix** [comment]
Cool. When it comes to publishing `akka-kryo-serialization-shaded` do I need to do anything special?

Today, what I usually do is:
`sbt release`

**Comment by romix** [comment]
BTW, you seem to be pretty fluent when it comes to properly configuring `sbt`. I'd appreciate if you could have a look at the issues described here: #106. We even filed a separate issue related to that: #107 May be you know how to fix cross-builds or to use a new `sbt` syntax properly?

**Comment by Pacien** [comment]
My bad ; I forgot to take the following into account:
- running `sbt release` for each version may increment the version number twice,
- running `sbt release` and then `sbt akka-kryo-serialization-shaded/publishSigned` will use the `SNAPSHOT` version number for the latter.

I think it will be simpler to rewrite a new `build.sbt` as proposed in #107, fixing #106 too.
I'll probably come back onto that when I'll get some free time.

**Comment by guidomedina** [comment]
Dependencies maintenance is a tedious task, each project takes its time which forces one to do this,
not pretty but in the meantime it works, even `Kryo` (not `akka-kryo-serialization`) has its own dependencies out of date:
```
         <!-- Akka kryo -->
         <dependency>
            <groupId>com.github.romix.akka</groupId>
            <artifactId>akka-kryo-serialization_${scala.version}</artifactId>
            <version>0.5.2</version>
         </dependency>

         <!-- Kryo -->
         <dependency>
            <groupId>com.esotericsoftware</groupId>
            <artifactId>kryo</artifactId>
            <version>4.0.1</version>
         </dependency>

         <!-- Reflect ASM -->
       <dependency>
            <groupId>com.esotericsoftware</groupId>
            <artifactId>reflectasm</artifactId>
            <version>1.11.3</version>
         </dependency>

         <!-- ASM -->
         <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm</artifactId>
            <version>6.0</version>
         </dependency>
```

**Comment by nvollmar** [comment]
Hello @pacien 

Would you be willing to update the pull request as we moved on to `build.sbt`?

**Comment by pacien** [comment]
I'm afraid I don't personally need this anymore.

**Pull request closed without merging**
