### PR TITLE
Fixes thread-safety issues with deflate

### PR DESCRIPTION
**Pull request by nvollmar**
Uses new Deflater/Inflator per serialization to avoid race conditions

### CODE REVIEW

**Comment by nvollmar** [comment]
Before:
```
Serialized to 4355 bytes
Zip Immutable HashMap Serialize:   	257.0	ms	=	1945	ops/ms
Zip Immutable HashMap Serialize:   	203.1	ms	=	2462	ops/ms
Zip Immutable HashMap Serialize:   	199.0	ms	=	2512	ops/ms
Zip Immutable HashMap Deserialize: 	395.5	ms	=	1264	ops/ms
Zip Immutable HashMap Deserialize: 	207.5	ms	=	2410	ops/ms
Zip Immutable HashMap Deserialize: 	196.0	ms	=	2551	ops/ms
Serialized to 4369 bytes
Zip Immutable TreeMap Serialize:   	213.8	ms	=	2338	ops/ms
Zip Immutable TreeMap Serialize:   	205.7	ms	=	2431	ops/ms
Zip Immutable TreeMap Serialize:   	201.7	ms	=	2479	ops/ms
Zip Immutable TreeMap Deserialize: 	256.9	ms	=	1947	ops/ms
Zip Immutable TreeMap Deserialize: 	190.9	ms	=	2620	ops/ms
Zip Immutable TreeMap Deserialize: 	205.9	ms	=	2429	ops/ms
Serialized to 4311 bytes
Zip Immutable LongMap Serialize:   	198.1	ms	=	2524	ops/ms
Zip Immutable LongMap Serialize:   	188.4	ms	=	2653	ops/ms
Zip Immutable LongMap Serialize:   	188.7	ms	=	2650	ops/ms
Zip Immutable LongMap Deserialize: 	144.4	ms	=	3462	ops/ms
Zip Immutable LongMap Deserialize: 	125.5	ms	=	3984	ops/ms
Zip Immutable LongMap Deserialize: 	117.1	ms	=	4268	ops/ms
Serialized to 4371 bytes
Zip Mutable AnyRefMap Serialize:   	261.8	ms	=	1910	ops/ms
Zip Mutable AnyRefMap Serialize:   	234.9	ms	=	2128	ops/ms
Zip Mutable AnyRefMap Serialize:   	222.3	ms	=	2249	ops/ms
Zip Mutable AnyRefMap Deserialize: 	245.2	ms	=	2039	ops/ms
Zip Mutable AnyRefMap Deserialize: 	181.7	ms	=	2752	ops/ms
Zip Mutable AnyRefMap Deserialize: 	172.8	ms	=	2893	ops/ms
Serialized to 4355 bytes
Zip Mutable HashMap Serialize:   	224.8	ms	=	2224	ops/ms
Zip Mutable HashMap Serialize:   	224.0	ms	=	2232	ops/ms
Zip Mutable HashMap Serialize:   	218.4	ms	=	2289	ops/ms
Zip Mutable HashMap Deserialize: 	170.9	ms	=	2925	ops/ms
Zip Mutable HashMap Deserialize: 	167.7	ms	=	2982	ops/ms
Zip Mutable HashMap Deserialize: 	165.8	ms	=	3016	ops/ms
Serialized to 4311 bytes
Zip Mutable LongMap Serialize:   	218.2	ms	=	2292	ops/ms
Zip Mutable LongMap Serialize:   	222.5	ms	=	2248	ops/ms
Zip Mutable LongMap Serialize:   	226.5	ms	=	2208	ops/ms
Zip Mutable LongMap Deserialize: 	145.9	ms	=	3428	ops/ms
Zip Mutable LongMap Deserialize: 	143.1	ms	=	3495	ops/ms
Zip Mutable LongMap Deserialize: 	149.8	ms	=	3337	ops/ms
Serialized to 13971 bytes
Zip Immutable HashSet Serialize:   	414.6	ms	=	1206	ops/ms
Zip Immutable HashSet Serialize:   	400.9	ms	=	1247	ops/ms
Zip Immutable HashSet Serialize:   	386.9	ms	=	1292	ops/ms
Zip Immutable HashSet Deserialize: 	331.4	ms	=	1509	ops/ms
Zip Immutable HashSet Deserialize: 	297.7	ms	=	1680	ops/ms
Zip Immutable HashSet Deserialize: 	294.9	ms	=	1695	ops/ms
Serialized to 12918 bytes
Zip Immutable TreeSet Serialize:   	374.1	ms	=	1336	ops/ms
Zip Immutable TreeSet Serialize:   	369.4	ms	=	1354	ops/ms
Zip Immutable TreeSet Serialize:   	368.4	ms	=	1357	ops/ms
Zip Immutable TreeSet Deserialize: 	320.5	ms	=	1560	ops/ms
Zip Immutable TreeSet Deserialize: 	305.6	ms	=	1636	ops/ms
Zip Immutable TreeSet Deserialize: 	299.1	ms	=	1672	ops/ms
Serialized to 4062 bytes
Zip Immutable BitSet Serialize:   	222.3	ms	=	2249	ops/ms
Zip Immutable BitSet Serialize:   	196.7	ms	=	2542	ops/ms
Zip Immutable BitSet Serialize:   	191.6	ms	=	2609	ops/ms
Zip Immutable BitSet Deserialize: 	106.5	ms	=	4695	ops/ms
Zip Immutable BitSet Deserialize: 	85.7	ms	=	5832	ops/ms
Zip Immutable BitSet Deserialize: 	80.8	ms	=	6185	ops/ms
Serialized to 13661 bytes
Zip Mutable HashSet Serialize:   	381.8	ms	=	1309	ops/ms
Zip Mutable HashSet Serialize:   	369.3	ms	=	1354	ops/ms
Zip Mutable HashSet Serialize:   	373.4	ms	=	1339	ops/ms
Zip Mutable HashSet Deserialize: 	240.3	ms	=	2081	ops/ms
Zip Mutable HashSet Deserialize: 	229.8	ms	=	2176	ops/ms
Zip Mutable HashSet Deserialize: 	226.2	ms	=	2210	ops/ms
Serialized to 12921 bytes
Zip Mutable TreeSet Serialize:   	412.3	ms	=	1213	ops/ms
Zip Mutable TreeSet Serialize:   	367.6	ms	=	1360	ops/ms
Zip Mutable TreeSet Serialize:   	373.3	ms	=	1339	ops/ms
Zip Mutable TreeSet Deserialize: 	298.9	ms	=	1673	ops/ms
Zip Mutable TreeSet Deserialize: 	252.3	ms	=	1981	ops/ms
Zip Mutable TreeSet Deserialize: 	254.2	ms	=	1967	ops/ms
Serialized to 4125 bytes
Zip Mutable BitSet Serialize:   	200.1	ms	=	2498	ops/ms
Zip Mutable BitSet Serialize:   	201.8	ms	=	2478	ops/ms
Zip Mutable BitSet Serialize:   	195.2	ms	=	2562	ops/ms
Zip Mutable BitSet Deserialize: 	80.0	ms	=	6252	ops/ms
Zip Mutable BitSet Deserialize: 	79.1	ms	=	6317	ops/ms
Zip Mutable BitSet Deserialize: 	82.2	ms	=	6082	ops/ms
Serialized to 4661 bytes
Zip Vector Serialize:   	241.5	ms	=	2071	ops/ms
Zip Vector Serialize:   	235.9	ms	=	2119	ops/ms
Zip Vector Serialize:   	230.4	ms	=	2170	ops/ms
Zip Vector Deserialize: 	142.0	ms	=	3522	ops/ms
Zip Vector Deserialize: 	123.7	ms	=	4043	ops/ms
Zip Vector Deserialize: 	128.2	ms	=	3901	ops/ms
Serialized to 3686 bytes
Zip Array Serialize:   	107.4	ms	=	4656	ops/ms
Zip Array Serialize:   	105.8	ms	=	4726	ops/ms
Zip Array Serialize:   	111.4	ms	=	4487	ops/ms
Zip Array Deserialize: 	45.3	ms	=	11026	ops/ms
Zip Array Deserialize: 	42.8	ms	=	11678	ops/ms
Zip Array Deserialize: 	41.1	ms	=	12164	ops/ms
```

After:
```
Serialized to 4355 bytes
Zip Immutable HashMap Serialize:   	267.9	ms	=	1867	ops/ms
Zip Immutable HashMap Serialize:   	207.6	ms	=	2408	ops/ms
Zip Immutable HashMap Serialize:   	201.6	ms	=	2480	ops/ms
Zip Immutable HashMap Deserialize: 	245.8	ms	=	2034	ops/ms
Zip Immutable HashMap Deserialize: 	183.9	ms	=	2719	ops/ms
Zip Immutable HashMap Deserialize: 	192.2	ms	=	2601	ops/ms
Serialized to 4369 bytes
Zip Immutable TreeMap Serialize:   	238.9	ms	=	2093	ops/ms
Zip Immutable TreeMap Serialize:   	206.3	ms	=	2424	ops/ms
Zip Immutable TreeMap Serialize:   	202.6	ms	=	2468	ops/ms
Zip Immutable TreeMap Deserialize: 	288.2	ms	=	1735	ops/ms
Zip Immutable TreeMap Deserialize: 	196.8	ms	=	2541	ops/ms
Zip Immutable TreeMap Deserialize: 	196.3	ms	=	2548	ops/ms
Serialized to 4311 bytes
Zip Immutable LongMap Serialize:   	211.8	ms	=	2360	ops/ms
Zip Immutable LongMap Serialize:   	189.3	ms	=	2641	ops/ms
Zip Immutable LongMap Serialize:   	199.0	ms	=	2513	ops/ms
Zip Immutable LongMap Deserialize: 	145.2	ms	=	3445	ops/ms
Zip Immutable LongMap Deserialize: 	135.0	ms	=	3703	ops/ms
Zip Immutable LongMap Deserialize: 	141.0	ms	=	3546	ops/ms
Serialized to 4371 bytes
Zip Mutable AnyRefMap Serialize:   	352.3	ms	=	1419	ops/ms
Zip Mutable AnyRefMap Serialize:   	242.0	ms	=	2067	ops/ms
Zip Mutable AnyRefMap Serialize:   	241.6	ms	=	2069	ops/ms
Zip Mutable AnyRefMap Deserialize: 	209.8	ms	=	2383	ops/ms
Zip Mutable AnyRefMap Deserialize: 	200.9	ms	=	2489	ops/ms
Zip Mutable AnyRefMap Deserialize: 	202.8	ms	=	2465	ops/ms
Serialized to 4355 bytes
Zip Mutable HashMap Serialize:   	243.6	ms	=	2052	ops/ms
Zip Mutable HashMap Serialize:   	239.7	ms	=	2086	ops/ms
Zip Mutable HashMap Serialize:   	234.8	ms	=	2130	ops/ms
Zip Mutable HashMap Deserialize: 	175.3	ms	=	2853	ops/ms
Zip Mutable HashMap Deserialize: 	181.7	ms	=	2752	ops/ms
Zip Mutable HashMap Deserialize: 	183.6	ms	=	2723	ops/ms
Serialized to 4311 bytes
Zip Mutable LongMap Serialize:   	252.1	ms	=	1983	ops/ms
Zip Mutable LongMap Serialize:   	241.4	ms	=	2071	ops/ms
Zip Mutable LongMap Serialize:   	232.6	ms	=	2149	ops/ms
Zip Mutable LongMap Deserialize: 	155.2	ms	=	3221	ops/ms
Zip Mutable LongMap Deserialize: 	158.1	ms	=	3163	ops/ms
Zip Mutable LongMap Deserialize: 	151.7	ms	=	3296	ops/ms
Serialized to 13971 bytes
Zip Immutable HashSet Serialize:   	436.9	ms	=	1145	ops/ms
Zip Immutable HashSet Serialize:   	404.2	ms	=	1237	ops/ms
Zip Immutable HashSet Serialize:   	438.7	ms	=	1140	ops/ms
Zip Immutable HashSet Deserialize: 	370.8	ms	=	1348	ops/ms
Zip Immutable HashSet Deserialize: 	328.5	ms	=	1522	ops/ms
Zip Immutable HashSet Deserialize: 	314.9	ms	=	1588	ops/ms
Serialized to 12918 bytes
Zip Immutable TreeSet Serialize:   	412.2	ms	=	1213	ops/ms
Zip Immutable TreeSet Serialize:   	393.2	ms	=	1272	ops/ms
Zip Immutable TreeSet Serialize:   	382.9	ms	=	1306	ops/ms
Zip Immutable TreeSet Deserialize: 	376.3	ms	=	1329	ops/ms
Zip Immutable TreeSet Deserialize: 	319.0	ms	=	1568	ops/ms
Zip Immutable TreeSet Deserialize: 	321.3	ms	=	1556	ops/ms
Serialized to 4062 bytes
Zip Immutable BitSet Serialize:   	221.9	ms	=	2253	ops/ms
Zip Immutable BitSet Serialize:   	201.2	ms	=	2485	ops/ms
Zip Immutable BitSet Serialize:   	199.8	ms	=	2503	ops/ms
Zip Immutable BitSet Deserialize: 	96.4	ms	=	5188	ops/ms
Zip Immutable BitSet Deserialize: 	84.0	ms	=	5953	ops/ms
Zip Immutable BitSet Deserialize: 	84.8	ms	=	5898	ops/ms
Serialized to 13661 bytes
Zip Mutable HashSet Serialize:   	396.2	ms	=	1262	ops/ms
Zip Mutable HashSet Serialize:   	402.5	ms	=	1242	ops/ms
Zip Mutable HashSet Serialize:   	385.3	ms	=	1298	ops/ms
Zip Mutable HashSet Deserialize: 	239.3	ms	=	2089	ops/ms
Zip Mutable HashSet Deserialize: 	236.4	ms	=	2115	ops/ms
Zip Mutable HashSet Deserialize: 	233.2	ms	=	2145	ops/ms
Serialized to 12921 bytes
Zip Mutable TreeSet Serialize:   	431.6	ms	=	1158	ops/ms
Zip Mutable TreeSet Serialize:   	431.5	ms	=	1159	ops/ms
Zip Mutable TreeSet Serialize:   	424.7	ms	=	1177	ops/ms
Zip Mutable TreeSet Deserialize: 	327.4	ms	=	1527	ops/ms
Zip Mutable TreeSet Deserialize: 	283.1	ms	=	1766	ops/ms
Zip Mutable TreeSet Deserialize: 	276.1	ms	=	1811	ops/ms
Serialized to 4125 bytes
Zip Mutable BitSet Serialize:   	203.7	ms	=	2454	ops/ms
Zip Mutable BitSet Serialize:   	207.4	ms	=	2410	ops/ms
Zip Mutable BitSet Serialize:   	228.4	ms	=	2189	ops/ms
Zip Mutable BitSet Deserialize: 	101.3	ms	=	4936	ops/ms
Zip Mutable BitSet Deserialize: 	104.6	ms	=	4779	ops/ms
Zip Mutable BitSet Deserialize: 	99.5	ms	=	5027	ops/ms
Serialized to 4661 bytes
Zip Vector Serialize:   	284.5	ms	=	1757	ops/ms
Zip Vector Serialize:   	259.0	ms	=	1930	ops/ms
Zip Vector Serialize:   	252.8	ms	=	1978	ops/ms
Zip Vector Deserialize: 	148.2	ms	=	3374	ops/ms
Zip Vector Deserialize: 	148.4	ms	=	3368	ops/ms
Zip Vector Deserialize: 	132.4	ms	=	3777	ops/ms
Serialized to 3686 bytes
Zip Array Serialize:   	126.6	ms	=	3949	ops/ms
Zip Array Serialize:   	130.0	ms	=	3846	ops/ms
Zip Array Serialize:   	124.3	ms	=	4024	ops/ms
Zip Array Deserialize: 	46.7	ms	=	10714	ops/ms
Zip Array Deserialize: 	45.2	ms	=	11073	ops/ms
Zip Array Deserialize: 	43.7	ms	=	11430	ops/ms
```

**Comment by danischroeter** [comment]
this might be the underlying issue: https://bugs.openjdk.java.net/browse/JDK-8161903

**Comment by nvollmar** [comment]
Refs #123

**Comment by danischroeter** [comment]
since there was ONE global Defaltor/Inflator and they used synchronized this must have blocked / limit concurrency massively - I expect performance improves with this change in concurrent situations...

**Pull request merged**
