### PR TITLE
Fixes for #107, #129

### PR DESCRIPTION
**Pull request by ajaychandran**
Fix for #129

### CODE REVIEW

**Comment by ajaychandran** [comment]
@luben @romix 
Hi, could you please take a look at this? Thanks.

**Comment by luben** [comment]
+1 both changes look good to me

**Comment by ajaychandran** [comment]
Thanks @luben 
Would it be possible to test the settings for a snapshot version?

**Comment by luben** [comment]
I guess only @romix can test if it works as expected

**Comment by altooag** [comment]
Hi @ajaychandran 
We just took over maintenance of the project and are now cleaning up tickets/pull requests. There have been multiple PR's doing the sbt upgrade - we picket #142 and also updated all dependencies... etc.
Could you create a new pr and only address #129 if this is still an issue pls?

**Pull request closed without merging**
